name: Build package release .zip file

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Alte Artefakte löschen
      - name: Clean old build files
        run: rm -rf react-json-view *.zip

      # Composer-Abhängigkeiten installieren
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      # Release-Ordner vorbereiten
      - name: Prepare release folder
        run: |
          mkdir react-json-view
          cp -r dist package.json index.d.ts README.md LICENSE.md react-json-view/

      # TAR.GZ erstellen
      - name: Create TAR.GZ archive
        run: tar -czf package.tar.gz -C react-json-view .

      # ZIP als Release-Asset hochladen
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: package.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
